server:
  port: 5004

spring:
  application:
    name: analysticservice
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/getrand?serverTimezone=UTC
    username: mytest
    password: 1234

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
  instance:
# 2초동안 하트비트가 수신되지 않으면 서비스 등록을 해제
    lease-expiration-duration-in-seconds: 2

logging:
  level:
    org:
      hibernate:
        sql: debug
        type:
          descriptor:
            sql: trace